### ISSUE TITLE
Preferred Feedback Channel: Issues and PRs or Internal Communications

### ISSUE THREAD

**Issue by rajesh-nayak-cms** [CMSgov/cms-open-source-policy#1]
Does CMS want to develop this policy in the open, as open source itself, via GitHub issues & PRs or via internal communications (like this email)? I’m happy to accommodate whichever the preferred mechanism is. It’s worth noting, though, that the policy is currently written in a way that makes it sound like public channels (issues & PRs) are preferred, in this “Future changes” section: https://github.com/CMSgov/cms-open-source-policy/blob/master/Policy.md#future-changes.

**Comment by decause-gov** [comment]
Yes, public issues and pull requests are the preferred way to make future changes to the policy :)
