### ISSUE TITLE
Public Domain vs. Copyright

### ISSUE THREAD

**Issue by rajesh-nayak-cms** [CMSgov/cms-open-source-policy#2]
There’s a conflict between this sentence:

 

> Several CMS projects have preferred to dedicate their work in the Public Domain

 

Versus this clause:

 

> Once an appropriate license is chosen for the project, the full license text should be included in the ‘license’ file of the distribution bundle. Each source code must have a notice at the top to name CMS, or an organization designated explicitly by CMS as the copyright and license holder of the source code and provide a link to the full text of the license.

Public domain is a waiving of copyright (more or less), so if something is in the public domain, it doesn’t make sense to mark it as being copyrighted by CMS.

**Comment by decause-gov** [comment]
Our v1.1 release should resolve this issue in the `License` section.
