### ISSUE TITLE
Requirements vs. Suggestions

### ISSUE THREAD

**Issue by rajesh-nayak-cms** [CMSgov/cms-open-source-policy#4]
> The project team should implement tools to support the community around an open source project, such as mailing lists, message forums, a version control, wiki, and tracking mechanisms, such as Kanban boards to track issues and bugs on the GitHub repository.

 

It’s typical for policies like this to use SHALL for requirements and SHOULD for suggestions, but it’s not clear if that’s what’s happening here. If it is, I would suggest explicitly referencing RFC 2119 (https://tools.ietf.org/html/rfc2119) and capitalizing the words to call them out, per that RFC.

**Comment by decause-gov** [comment]
As of v1.1, SHOULD is the correct term used here, as per RFC 2119 referenced above. Future versions will take this issue into consideration if we make any changes. Thank you for bringing this to our attention.
