### ISSUE TITLE
CC01 and patent provision 

### ISSUE THREAD

**Issue by andres-gov** [CMSgov/cms-open-source-policy#5]
A team I'm supporting has been considering public domain, specifically CC01 for a project we're open sourcing at CMS.  Based on some of the internal discussion, despite CC01 being used quite a bit at CMS, it may present an issue in regards to not addressing patent provisions. Seems like CC01 could present a legal hazard in relation to patents. Given the US government holds a lot of patents, it would be good to evaluate if we should continue to highlight CC01 within the policy as a option for CMS. 

Any thoughts in relation to keeping it as a default or providing additional clarification? @rajesh-nayak-cms

**Comment by decause-gov** [comment]
@andres-gov Thank you for your support of Open Source at CMS.

I am working with the Digital Service here at CMS to review our Open Source Policies, and will include this question in our review process. In the meantime, you can join #cms-opensource on slack, happy to discuss there.

**Comment by decause-gov** [comment]
@andres-gov I will start with the standard disclaimer of "I am not a lawyer and this does not constitute legal or financial advice."

Based upon analysis of the most recently updated Open Source Policies and best practices from other Federal agencies such as [GSA](https://github.com/GSA/open-source-policy/blob/master/policy.md#open-source-licenses) and [CISA](https://github.com/cisagov/development-guide/blob/develop/open-source-policy/policy.md#open-source-licenses), CC0 remains the recommended default public domain designation mechanism for Federal Open Source Code.

For additional information about software patent considerations, you can read more in the [DOD OSS FAQ](https://dodcio.defense.gov/Open-Source-Software-FAQ/) by searching for "software patents" in the text.
